name: CI 

on:
  push:
    branches:
    - 'main'
  pull_request:
    types: [opened]
  issue_comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'retest please')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: coursier/cache-action@v5
      - name: Build backend
        run: sbt compile
      - name: Build site
        run: sbt build
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
