name: CI 

on: [pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: coursier/cache-action@v5
      - name: Build backend
        run: sbt compile
      - name: Build site
        run: sbt build
